-- begin BPMAPP_SUBDIVISION
alter table BPMAPP_SUBDIVISION add constraint FK_BPMAPP_SUBDIVISION_ON_HEAD_OF_DEPARTMENT foreign key (HEAD_OF_DEPARTMENT_ID) references BPMAPP_EMPLOYEE(ID)^
alter table BPMAPP_SUBDIVISION add constraint FK_BPMAPP_SUBDIVISION_ON_LEADING_SUBDIVISION foreign key (LEADING_SUBDIVISION_ID) references BPMAPP_SUBDIVISION(ID)^
create index IDX_BPMAPP_SUBDIVISION_ON_HEAD_OF_DEPARTMENT on BPMAPP_SUBDIVISION (HEAD_OF_DEPARTMENT_ID)^
create index IDX_BPMAPP_SUBDIVISION_ON_LEADING_SUBDIVISION on BPMAPP_SUBDIVISION (LEADING_SUBDIVISION_ID)^
-- end BPMAPP_SUBDIVISION
-- begin BPMAPP_EMPLOYEE
alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_SUBDIVISION foreign key (SUBDIVISION_ID) references BPMAPP_SUBDIVISION(ID)^
alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
create index IDX_BPMAPP_EMPLOYEE_ON_USER on BPMAPP_EMPLOYEE (USER_ID)^
create index IDX_BPMAPP_EMPLOYEE_ON_SUBDIVISION on BPMAPP_EMPLOYEE (SUBDIVISION_ID)^
create index IDX_BPMAPP_EMPLOYEE_ON_PHOTO on BPMAPP_EMPLOYEE (PHOTO_ID)^
-- end BPMAPP_EMPLOYEE
-- begin BPMAPP_OUTGOING_DOCUMENT
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references BPMAPP_DOCUMENT(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_JOURNAL foreign key (JOURNAL_ID) references BPMAPP_JOURNAL(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_CAUSE foreign key (CAUSE_ID) references BPMAPP_NOMENCLATURE(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_SIGNATORY foreign key (SIGNATORY_ID) references BPMAPP_EMPLOYEE(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_COORDINATOR foreign key (COORDINATOR_ID) references BPMAPP_EMPLOYEE(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_EXECUTOR foreign key (EXECUTOR_ID) references BPMAPP_EMPLOYEE(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE on BPMAPP_OUTGOING_DOCUMENT (DOCUMENT_TYPE_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_JOURNAL on BPMAPP_OUTGOING_DOCUMENT (JOURNAL_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_CAUSE on BPMAPP_OUTGOING_DOCUMENT (CAUSE_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_SIGNATORY on BPMAPP_OUTGOING_DOCUMENT (SIGNATORY_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_COORDINATOR on BPMAPP_OUTGOING_DOCUMENT (COORDINATOR_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_EXECUTOR on BPMAPP_OUTGOING_DOCUMENT (EXECUTOR_ID)^
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_AUTHOR on BPMAPP_OUTGOING_DOCUMENT (AUTHOR_ID)^
-- end BPMAPP_OUTGOING_DOCUMENT
-- begin BPMAPP_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK
alter table BPMAPP_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_OUTDOCFILDES_ON_OUTGOING_DOCUMENT foreign key (OUTGOING_DOCUMENT_ID) references BPMAPP_OUTGOING_DOCUMENT(ID)^
alter table BPMAPP_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_OUTDOCFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end BPMAPP_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK
