alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_SUBDIVISION foreign key (SUBDIVISION_ID) references BPMAPP_SUBDIVISION(ID);
alter table BPMAPP_EMPLOYEE add constraint FK_BPMAPP_EMPLOYEE_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID);
create index IDX_BPMAPP_EMPLOYEE_ON_USER on BPMAPP_EMPLOYEE (USER_ID);
create index IDX_BPMAPP_EMPLOYEE_ON_SUBDIVISION on BPMAPP_EMPLOYEE (SUBDIVISION_ID);
create index IDX_BPMAPP_EMPLOYEE_ON_PHOTO on BPMAPP_EMPLOYEE (PHOTO_ID);
