alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references BPMAPP_DOCUMENT(ID);
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_EXECUTOR foreign key (EXECUTOR_ID) references BPMAPP_EMPLOYEE(ID);
alter table BPMAPP_OUTGOING_DOCUMENT add constraint FK_BPMAPP_OUTGOING_DOCUMENT_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID);
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE on BPMAPP_OUTGOING_DOCUMENT (DOCUMENT_TYPE_ID);
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_EXECUTOR on BPMAPP_OUTGOING_DOCUMENT (EXECUTOR_ID);
create index IDX_BPMAPP_OUTGOING_DOCUMENT_ON_AUTHOR on BPMAPP_OUTGOING_DOCUMENT (AUTHOR_ID);
